name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target universal-apple-darwin'
            target: 'universal-apple-darwin'
            arch: 'universal'
          - platform: 'ubuntu-22.04'
            args: ''
            target: 'x86_64-unknown-linux-gnu'
            arch: 'x86_64'
          - platform: 'windows-latest'
            args: ''
            target: 'x86_64-pc-windows-msvc'
            arch: 'x86_64'

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './tauri-gui/src-tauri -> target'

      - name: Sync node version and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: './tauri-gui/package-lock.json'

      - name: Install frontend dependencies
        working-directory: ./tauri-gui
        run: npm ci

      - name: Build the app
        working-directory: ./tauri-gui
        run: npm run tauri build -- ${{ matrix.args }}

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            tauri-gui/src-tauri/target/${{ matrix.target }}/release/bundle/dmg/*.dmg
            tauri-gui/src-tauri/target/${{ matrix.target }}/release/bundle/deb/*.deb
            tauri-gui/src-tauri/target/${{ matrix.target }}/release/bundle/appimage/*.AppImage
            tauri-gui/src-tauri/target/${{ matrix.target }}/release/bundle/msi/*.msi
            tauri-gui/src-tauri/target/${{ matrix.target }}/release/bundle/nsis/*.exe
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}