name: Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.2.x
          dune-cache: false

      - name: Install OCaml dependencies
        run: opam install -y camlpdf sqlite3 dune alcotest

      - name: Run OCaml tests and build
        working-directory: ./ocaml-backend
        run: |
          eval $(opam env)
          dune runtest
          dune build

  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"
          cache-dependency-path: "./package-lock.json"

      - name: Install frontend dependencies
        working-directory: .
        run: npm ci

      - name: Check JavaScript/TypeScript formatting
        working-directory: .
        run: |
          # Add any linting commands here when available
          echo "No linting configured yet"

      - name: Install Rust dependencies (ubuntu only)
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev patchelf

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Check Rust formatting
        working-directory: ./tauri
        run: cargo fmt --all -- --check

      - name: Run Rust linting
        working-directory: ./tauri
        run: cargo clippy -- -D warnings
